name: gpu-binder
channels:
    - nvidia
    - anaconda
    - conda-forge
dependencies:
#   - tensorflow-gpu
  - pip
  - cudatoolkit-dev=10
  - cudnn=7.6
  - matplotlib
  - keras-gpu
  - cxx-compiler
  - python=3.7
  - gcc_linux-64=7.3
  - nvcc_linux-64
  - nccl
  - cmake
  - nvidia-ml
  - cupti
#   - torch
#   - tensorflow=2.3
  - nodejs
  - ipython
  - jupyter
  - jupyterlab=2.2.0
  - jupyter_contrib_nbextensions
  - jupyter_nbextensions_configurator
  - jupyterlab_widgets
  - opencv
  - pip:
    - tensorflow==2.3
    - jupyterlab-git
    - -r file:requirements.txt
#     - torch

